# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_app', '0004_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rate',
            field=models.CharField(max_length=8),
        ),
    ]
